- Cargo.toml
- README.md
tiddy up before releasing the crates on crates.io
> change upstream

- Cargo.toml
last step before pushing to crates.io
we need pinned dependencies and a description
Sorry for all those PR, I'm not a crates.io expert :stuck_out_tongue:
> Add description and pin version

- Cargo.toml
- README.md
- examples/from_geo.rs
- examples/prepared_geom.rs
- examples/verbose_example.rs
- src/error.rs
- src/ffi.rs
- src/from_geo.rs
- src/test.rs
lots of geos operation can fail so we wrap those in Result to remove every `panic!`
I bumped the version number as this breaks the api
> uses Results everywhere

- Cargo.toml
- src/ffi.rs
Also use `std::ptr::NonNull` for better abstraction.
> Remove Clone from PreparedGGeom as it is unsound.

- Cargo.toml
- examples/from_geo.rs
- src/from_geo.rs
- src/lib.rs
> Use geo-types crate

- Cargo.toml
- README.md
- src/ffi.rs
- src/test.rs
Fixes https://github.com/georust/geos/issues/20.
> Deprecate to_wkt_precison, introduce to_wkt_precision.

- Cargo.toml
- examples/from_geo.rs
- src/from_geo.rs
- src/voronoi.rs
```
$ cargo outdated
All dependencies are up to date, yay!
```
> update all dependencies

- Cargo.toml
- README.md.skt.md
- examples/from_geo.rs
- examples/prepared_geom.rs
- examples/verbose_example.rs
- src/error.rs
- src/lib.rs
> Remove failure

- src/enums.rs
- src/ffi.rs
- src/functions.rs
- src/geom.rs
- src/lib.rs
> Improvements

- .travis.yml
- Cargo.toml
- README.md
- build.rs
- examples/from_geo.rs
- examples/prepared_geom.rs
- examples/verbose_example.rs
- src/context_handle.rs
- src/coord_seq.rs
- src/enums.rs
- src/ffi.rs
- src/from_geo.rs
- src/functions.rs
- src/geom.rs
- src/lib.rs
- src/prepared_geom.rs
- src/test.rs
- src/to_geo.rs
- src/traits.rs
- src/voronoi.rs
- tests/skeptic.rs
@TeXitoi Does the API looks better this way? If so, we'll have to add a lot more examples in the docs stating that setting `GContextHandle` inside an object is better than just calling the object.
> Implement ContextHandle inside GGeom directly

- .travis.yml
- Cargo.toml
- examples/from_geo.rs
- examples/prepared_geom.rs
- examples/verbose_example.rs
- src/context_handle.rs
- src/coord_seq.rs
- src/enums.rs
- src/error.rs
- src/from_geo.rs
- src/from_geojson.rs
- src/functions.rs
- src/geometry.rs
- src/lib.rs
- src/prepared_geometry.rs
- src/spatial_index.rs
- src/test.rs
- src/to_geo.rs
- src/to_geojson.rs
- src/traits.rs
- src/voronoi.rs
- src/wkb_writer.rs
- src/wkt_writer.rs
* Update to geos-sys 2.0
* Strenghten checks on *const/*mut usage by creating a new AsRawMut trait
* Create a new ConstGeometry type to better handle the split with Geometry
> Update to geos-sys 2.0 and fix multiple issues

- src/lib.rs
> Export the JoinStyle enum

- sys/README.md
> Extend contributions explanations

- Cargo.toml
Fixes https://github.com/georust/geos/issues/82.
> Update geojson version to 0.24

- src/coord_seq.rs
I'm very inexperienced at C/rust ffi, so happy to get some feedback before adding all four functions and tests.
Closes https://github.com/georust/geos/issues/117
> Implement `copyFromBuffer`, `copyFromArrays`, `copyToBuffer` and `copyToArrays`

- src/from_geo.rs
While working with `geos` and `geo_types` I saw that conversion from `geo_types` to `geos` wasn't implemented for `MultiLineString` nor `MultiPoint`.
The changes are very trivial but I added a test for both cases.
> Add conversion from `geo_types::MultiPoint` and `geo_types::MultiLineString`

- sys/geos-src/Cargo.toml
Related to https://github.com/georust/geos/pull/144.
> Update `geos-src` version to 0.2.2

- src/geometry.rs
- src/prepared_geometry.rs
> Missing lifetime

- .github/workflows/CI.yml
- src/geometry.rs
> Update actions/cache to v4

- src/enums.rs
> Fix `Precision` enum values

- src/geometry.rs
Add missing geometry type checks for `project`, `project_normalized`, `get_num_interior_rings`, `get_interior_ring_n`, `get_exterior_ring`.
> Add missing geometry type checks
