georust/geos

Cargo.toml
src/ffi.rs
src/from_geo.rs

A closed ring with only 2 points was crashing libgeos
the ring: [p1, p2, p1] is not valid for geos (and it thus crashes without any nice explanation).
We use the same approach as [shapely](https://shapely.readthedocs.io) a quite used geos python wrapper and  
* we close the unclosed `LinearRing`
* we consider the 2 points closed ring as a 3 points unclosed ring (with the 2 last points beeing at the same position :laughing: ) and thus close it too.
Since it was the last blocking bug for us, I propose to bump the crate version to `1.0.0` to express the fact that it will soon be used in production somewhere :stuck_out_tongue_winking_eye:

Fix CoordSeq bug

---

Cargo.toml
README.md
examples/from_geo.rs
examples/prepared_geom.rs
examples/verbose_example.rs
src/error.rs
src/ffi.rs
src/from_geo.rs
src/test.rs

This PR wraps the result of the various binary predicates on `GGeom` and `PreparedGGeom` in a `GeosResult` in order to fix #10 .
I wanted to include a test case but I can't figure out how to trigger such an exception for now.
It bumps the version number to 1.1.0 as it breaks the API.

Return a GeosResult on the various binary predicate methods

---

Cargo.toml
src/ffi.rs
src/from_geo.rs

As a breaking change, `*::new_from_c_obj` are now private.
Use clean unsafe tagging and conventions.
Fix #13

ffi cleanups

---

Cargo.toml
README.md
README.md.skt.md
build.rs
tests/skeptic.rs

By this PR I propose to use rust-skeptic to test the code snippets present in the README (@antoine-de you suggested it while discussing one of my previous PR).
We do not have many examples in this file but I think it can still be useful (it made me see a missing `?` :))
The main drawback I can see is it adds a `tests` directory only for `skeptic` (maybe other integration tests will be added to it at some point, so it's not that bad?)

Use skeptic to test code snippets in readme file

---

.travis.yml
Cargo.toml
README.md
examples/from_geo.rs
examples/verbose_example.rs
src/error.rs
src/ffi.rs
src/from_geo.rs
src/lib.rs
src/to_geo.rs
src/voronoi.rs

add a binding to the libgeos [voronoi computation function](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in#L1710-L1714).
To use it more easily with [rust-geo](https://github.com/georust/geo) I added a simple wrapper to the geos binding.
It can thus be used either with pure geos:
```rust
let points = "MULTIPOINT ((150 200), (180 270), (275 163))";
let input = GGeom::new(points)?;
let voronoi = input.voronoi(None, 0., false)?;
```
or with rust-geo:
```rust
use geo_types::Point;
let points = vec![
Point::new(0., 0.),
Point::new(0., 1.),
Point::new(1., 1.),
Point::new(1., 0.),
];
let _voronoi = geos::compute_voronoi(&points, 0.)?;
```
For the moment to make the `geos -> geo` conversion, since I don't have much time (It's my last day in my current position :tada: ) I used …

Implement voronoi binding

---

src/main.rs

I guess it just adds noise in the `src` folder (and it's pretty uncommon for `lib` crates).

Remove useless main.rs file

---

src/ffi.rs
src/test.rs

This PR adds `create_multilinestring` and `create_geometrycollection` methods (fixes #27) and forces to check the type of each geometry given in argument in `create_multipoint`, `create_multilinestring` and `create_multipolygon` methods (fixes #29).

Add create_multilinestring and create_geometrycollection

---

src/lib.rs
src/spatial_index.rs

Basic STRtree wrapper with insert and query methods. I'm fairly new to Rust, so I wasn't sure about the correct way to store (references to) items in the tree. The proposed implementation introduces a generic type parameter <I> corresponding to the type of items that can be inserted into the tree. Internally, items are boxed and the raw pointer is passed to the GEOS implementation. When the tree is dropped, the implementation ensures that those pointers are freed.

feat: Add basic STRtree wrapper

---

src/functions.rs

Hardcoding the pointer type as `*const i8` causes the build to fail on the `armv7` platform and possibly other ARM-based targets as well. Changing this to `c_char` is a more general solution that makes `geos` compilable for multiple target architectures.

Fixes bug in armv7 build

---

.travis.yml
Cargo.toml
src/from_geojson.rs
src/lib.rs
src/test.rs
src/to_geojson.rs

This PR propose to add a `json` feature flag to handle the conversion from / to [geojson](https://github.com/georust/geojson) crate (instead of having to create [geo-type](https://github.com/georust/geo) geometries - themselves relying on WKT - to do it).

Allow conversion from/to GeoJSON

---

src/error.rs

Geos is excellent binding library, but there is one inconvenience.
When we try to catch the error returned from geos in Boxed error trait or anyhow::Error with `?` operator, it fails to compile, e.g.
```rust
use geos::Geom;
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
let gg1 = geos::Geometry::new_from_wkt("POLYGON ((0 0, 0 5, 6 6, 6 0, 0 0))")?;
let gg2 = geos::Geometry::new_from_wkt("POLYGON ((1 1, 1 3, 5 5, 5 1, 1 1))")?;
let gg3 = gg1.difference(&gg2)?;
assert_eq!(
gg3.to_wkt_precision(0).expect("to_wkt failed"),
"POLYGON ((0 0, 0 5, 6 6, 6 0, 0 0), (1 1, 5 1, 5 5, 1 3, 1 1))",
);
Ok(())
}
```
```rust
use geos::Geom;
use anyhow::Result;
fn main() -> Result<()> {
let gg1 = geos::Geometry::new_from_wkt("POLYGON ((0 0, 0 5, 6 6, 6 0, 0 0))")?;
let gg2 = …
```

Implement std::error::Error for geos::Error

---

src/prepared_geometry.rs

```
#20 199.4    Compiling geos v8.0.0
#20 202.9 error[E0308]: mismatched types
#20 202.9   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/geos-8.0.0/src/prepared_geometry.rs:93:30
#20 202.9    |
#20 202.9 93 |         check_geos_predicate(ret_val, PredicateType::PreparedContains)
#20 202.9    |                              ^^^^^^^ expected `i8`, found `u8`
#20 202.9    |
#20 202.9 help: you can convert a `u8` to an `i8` and panic if the converted value doesn't fit
#20 202.9    |
#20 202.9 93 |         check_geos_predicate(ret_val.try_into().unwrap(), PredicateType::PreparedContains)
#20 202.9    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#20 202.9 
#20 202.9 error[E0308]: mismatched types
#20 202.9    --> …
```

Fixed issue causing build to break on ARM.

---

README.md
src/geometry.rs
src/voronoi.rs
sys/README.md

This updates and simplifies the tests that were breaking on GEOS > 3.6 so that they run on all versions 3.6 - 3.11.
I understand that some of the doctests use geometires from the PostGIS documentation.  However, these are more complex than necessary for simple examples, so I simplified these down for clarity and to ensure they pass.

TST: Update tests to pass on GEOS 3.6 - 3.11

---

README.md

This fixes the 'from_geo' example in the README (and so in the doc generated by `cargo doc`, as it includes the README) by removing the `use geos::from_geo::TryInto;` statement (otherwise cargo complains that this trait is private).

Fix 'from_geo' example in README

---

README.md
geos-sys-bind/README.md

This updates the pinned version of GEOS for the `static` feature to 3.11.2 ([changelog](https://libgeos.org/posts/2023-03-16-geos-3-11-2-released/)).
This compiles successfully on GCC-12 and clang-14 (tested on `debian:unstable` Docker container)
/cc @jayvdb

MNT: Update GEOS source to 3.11.2

---

src/voronoi.rs

Adds a comment describing the tolerance parameter of the compute_voronoi function. This is useful as the parameter is described as finicky by the underlying c library. Having this comment would have saved me a headache.
Open to suggestions on better ways to expose this information.

Add-descriptive-comment-to-comput_vornoi-function-tolerance-parameter

---

README.md

Fixes compilation error with clang 16 and gcc 13 (missing 'cstdint' header).

Update GEOS source to 3.11.3

---

Cargo.lock
src/buffer_params.rs
src/context_handle.rs
src/coord_seq.rs
src/from_geo.rs
src/from_geojson.rs
src/functions.rs
src/geometry.rs
src/prepared_geometry.rs
src/spatial_index.rs
src/to_geo.rs
src/to_geojson.rs
src/traits.rs
src/wkb_writer.rs
src/wkt_writer.rs
sys/Cargo.toml

Fixes https://github.com/georust/geos/issues/152 and `2) Lifetimes` part of https://github.com/georust/geos/issues/141

Removed unnecessary lifetimes

---

src/geometry.rs

Applies an XY coordinate transform callback to all coordinates in a copy of input geometry
Wraps the GEOSGeom_transformXY_r function 
The trampoline functions for storing a rust closure and passing that as the userdata to the c function is inspired by:
https://adventures.michaelfbryan.com/posts/rust-closures-in-ffi/

transform_xy method on the Geom trait

---

src/geometry.rs

Failed call to `GEOSGetNumGeometries_r` is signaled by -1. Zero on the other hand is valid result when geometry is empty.

fix: get_num_geometries failing on empty geom

---

src/buffer_params.rs
src/context_handle.rs
src/coord_seq.rs
src/functions.rs
src/geometry.rs
src/lib.rs
src/prepared_geometry.rs
src/spatial_index.rs
src/traits.rs
src/wkb_writer.rs
src/wkt_writer.rs

This PR is follow-up of my previous issue #141 and also reaction to #160. (I don't think there is a memory leak, but this PR does lower memory footprint of every geometry by little more than 1kB as that is roughly the size of geos context, which would be reused with my PR and not allocated for every geometry.)
I see geos context as just an implementation detail of propagating error messages from c++ geos exceptions through geos c api in reentrant way. To address questions in #141: I dont't think the context is useful from user's point of view and I would say it is better/simpler to not have it in public api at all. I also think that context should not be a property of geometry for the same reason (and because unnecessarily used memory). And also I don't see it useful to be able to set own …

Tthread-local geos context

---

src/from_geo.rs

...and also TryFrom<geo_types::GeometryCollection>
I noticed that these two trait implementations were missing, and they seemed like they'd be useful inclusions. Each is sort of necessary to implement the other: a `Geometry` can wrap a `GeometryCollection`, and a `GeometryCollection` is made up of `Geometry`s (in order to wrap the heterogeneous members in a uniform type). The unit test I added exercises both conversions.
Feedback is very welcome.

Implement TryFrom<geo_types::Geometry> for GEOS Geometry

---

src/geojson_writer.rs
src/geometry.rs
src/lib.rs

This PR adds a new struct `GeoJSONWriter` with same properties and implementation as `WKTWriter`.  Just like GEOS C++ API, writing is done with the two methods:
```rs
pub fn write<G: Geom>(&mut self, geometry: &G) -> GResult<String>;
pub fn write_formatted<G: Geom>(&mut self, geometry: &G, indent: i32) -> GResult<String>;
```
The writer can be called with the two added functions in the Geometry trait:
```rs
fn to_geojson(&self) -> GResult<String>;
fn to_geojson_formatted(&self, indent: i32) -> GResult<String>;
```
Finally, the function `new_from_geojson` is also added to the Geometry trait to bring parity with `new_from_wkt`.

Add bindings to GEOSGeoJSONWriter and `new_from_geojson`

---

src/context_handle.rs
src/enums.rs
src/functions.rs
src/wkb_writer.rs
src/wkt_writer.rs

The rationale is that since they're mostly going to be user among other geos functions, it avoids having to repeatedly  cast their error type manually.

Change enums Error type from `&'static str` to `crate::error::Error`

---

src/geometry.rs
src/to_geojson.rs

This is to make it consistent with `get_point_n` and `get_geometry_n` which both accepts `usize`.

Change `get_interior_ring_n` parameter dtype to usize

---

src/geometry.rs

This PR prevents a crash when `project` is called on something else than a `LineString`.

Add `LineString` check for `project`

---

src/geometry.rs

This makes it in line with GEOS. This PR also contains a fix for geometries having -1 as an SRID, which is not an error code for `GEOSGetSRID_r` (0 is, but it's better to keep it that way, as it already implicetly means "no SRID").
Fixes https://github.com/georust/geos/issues/156

Change SRID type from usize to i32

---

src/from_geo.rs
src/from_geojson.rs
src/geometry.rs
src/to_geo.rs
src/to_geojson.rs

This is a refactor of the `Geom` and other `TryFrom` implementation, which remove the need for those hacky macro rules. It provides improved readability and allow formatting and linting to be run within (it wasn't the case before).
In order to achieve this, a new trait `OriginalGeometry` is introduced with a method `original`, which returns `self` for `Geometry` and `self.original` for `ConstGeometry` (maybe naming can be improved on that).

Remove most macro rules, so format and lint can run

---

examples/verbose_example.rs
src/buffer_params.rs
src/context_handle.rs
src/coord_seq.rs
src/error.rs
src/from_geo.rs
src/from_geojson.rs
src/functions.rs
src/geojson_writer.rs
src/geometry.rs
src/lib.rs
src/prepared_geometry.rs
src/spatial_index.rs
src/test.rs
src/to_geo.rs
src/to_geojson.rs
src/traits.rs
src/voronoi.rs
src/wkb_writer.rs
src/wkt_writer.rs

Sorry about the changes salad. Every point can be adressed separately, but splitting all this into different PRs would have been a bit too challenging.  First commit should be the more readable, as the second one involves moves of large chunks of unchanged code.
- Add macros `nullcheck`, `errcheck`, `predicate` to validate every GEOS call. This makes geometry type checking in rust unnecessary, and allows retrieving the actual GEOS error messages for all functions.
- Refactor `Geom` trait to merge declaration and implementation.
- Refactor `ContextHandler`.
- Remove errors `InvalidGeometry`, `GeosFunctionError`, `NoConstructionFromNullPtr`, `VoronoiError`, `NormalizeError`.
- Update `GenericError` and `GeosError` formatting.
- `transform_xy` now return `Result<_, E: From<geos::Error>>`. …

Add macros to validate every GEOS call (and much more)
